import { CategoryRoute } from './enums/category-route.enum'

export const PRODUCTS_CATEGORIES = [
  {
    i18nCode: CategoryRoute.driedFish,
    image: 'dried-fish.png',
    route: CategoryRoute.driedFish,
    items: [
      {
        i18nCode: 'beefJerky',
        image: '/products/beef-jerky.webp',
        price: 249.78,
        perKg: true,
      },
      {
        i18nCode: 'curedBullCarcass',
        image: '/products/cured-bull-carcass.webp',
        price: 36.24,
        perKg: false,
      },
      {
        i18nCode: 'driedVobla',
        image: '/products/dried-vobla.webp',
        price: 329.88,
        perKg: true,
      },
      {
        i18nCode: 'driedVomer',
        image: '/products/dried-vomer.webp',
        price: 200.94,
        perKg: true,
      },
      {
        i18nCode: 'driedSmelt',
        image: '/products/dried-smelt.webp',
        price: 35.94,
        perKg: false,
      },
      {
        i18nCode: 'driedBream',
        image: '/products/dried-bream.webp',
        price: 134.94,
        perKg: true,
      },
      {
        i18nCode: 'driedBreamFillet',
        image: '/products/dried-bream-fillet.webp',
        price: 20.34,
        perKg: false,
      },
      {
        i18nCode: 'driedGossip',
        image: '/products/dried-gossip.webp',
        price: 181.98,
        perKg: true,
      },
      {
        i18nCode: 'driedPlantain',
        image: '/products/dried-plantain.webp',
        price: 96.12,
        perKg: true,
      },
      {
        i18nCode: 'driedSalaka',
        image: '/products/dried-salaka.webp',
        price: 19.74,
        perKg: false,
      },
      {
        i18nCode: 'driedBruise',
        image: '/products/dried-bruise.webp',
        price: 118.38,
        perKg: true,
      },
      {
        i18nCode: 'driedPikePerch',
        image: '/products/dried-pike-perch.webp',
        price: 244.44,
        perKg: true,
      },
      {
        i18nCode: 'driedCatfishFillet',
        image: '/products/dried-catfish-fillet.webp',
        price: 372.84,
        perKg: true,
      },
    ],
  },
  {
    i18nCode: CategoryRoute.saltedFish,
    image: 'salted-fish.jpg',
    route: CategoryRoute.saltedFish,
    items: [
      {
        i18nCode: 'salmonFillet',
        image: '/products/salmon-fillet.webp',
        price: 580,
        perKg: true,
      },
      {
        i18nCode: 'slightlySaltSalaka',
        image: '/products/slightly-salt-salaka.webp',
        price: 47.48,
        perKg: false,
      },
    ],
  },
  {
    i18nCode: CategoryRoute.smokedFish,
    image: 'smoked-fish.jpg',
    route: CategoryRoute.smokedFish,
    items: [
      {
        i18nCode: 'bullCarcass',
        image: '/products/bull-carcass.webp',
        price: 40.68,
        perKg: false,
      },
      {
        i18nCode: 'coldSmokedSurmullet',
        image: '/products/cold-smoked-surmullet.webp',
        price: 261.96,
        perKg: true,
      },
      {
        i18nCode: 'coldSmokedVomer',
        image: '/products/cold-smoked-vomer.webp',
        price: 191.16,
        perKg: true,
      },
      {
        i18nCode: 'hotSmokedEel',
        image: '/products/hot-smoked-eel.webp',
        price: 236.04,
        perKg: true,
      },
      {
        i18nCode: 'coldSmokedPinkSalmon',
        image: '/products/cold-smoked-pink-salmon.webp',
        price: 230.88,
        perKg: true,
      },
      {
        i18nCode: 'coldSmokedBreamFilletAtlantic',
        image: '/products/cold-smoked-bream-fillet-atlantic.webp',
        price: 212.82,
        perKg: true,
      },
      {
        i18nCode: 'coldSmokedSmelt',
        image: '/products/cold-smoked-smelt.webp',
        price: 24.61,
        perKg: false,
      },
      {
        i18nCode: 'coldSmokedBreamLayer',
        image: '/products/cold-smoked-bream-layer.webp',
        price: 103.74,
        perKg: true,
      },
      {
        i18nCode: 'coldSmokedBream',
        image: '/products/cold-smoked-bream.webp',
        price: 108.96,
        perKg: true,
      },
      {
        i18nCode: 'coldSmokedSalaka',
        image: '/products/cold-smoked-salaka.webp',
        price: 27.78,
        perKg: false,
      },
      {
        i18nCode: 'coldSmokedBonito',
        image: '/products/cold-smoked-bonito.webp',
        price: 168,
        perKg: true,
      },
      {
        i18nCode: 'coldSmokedBreamFillet',
        image: '/products/cold-smoked-bream-fillet.webp',
        price: 95.04,
        perKg: true,
      },
    ],
  },
  {
    i18nCode: CategoryRoute.cannedFish,
    image: 'canned-fish.jpg',
    route: CategoryRoute.cannedFish,
    items: [
      {
        i18nCode: 'marinatedMussels',
        image: '/products/marinated-mussels.webp',
        price: 38.28,
        perKg: false,
      },
      {
        i18nCode: 'squidFilletFilling',
        image: '/products/squid-fillet-filling.webp',
        price: 33.48,
        perKg: false,
      },
      {
        i18nCode: 'koreanMarinatedSquid',
        image: '/products/korean-marinated-squid.webp',
        price: 25.02,
        perKg: false,
      },
      {
        i18nCode: 'koreanHerring',
        image: '/products/korean-herring.webp',
        price: 25.02,
        perKg: false,
      },
    ],
  },
]

export const HOME_PRODUCTS = [
  {
    i18nCode: 'marinatedMussels',
    categoryI18nCode: CategoryRoute.cannedFish,
    image: '/products/marinated-mussels.webp',
    price: 38.28,
    perKg: false,
  },
  {
    i18nCode: 'coldSmokedBonito',
    categoryI18nCode: CategoryRoute.smokedFish,
    image: '/products/cold-smoked-bonito.webp',
    price: 168,
    perKg: true,
  },
  {
    i18nCode: 'coldSmokedSmelt',
    categoryI18nCode: CategoryRoute.smokedFish,
    image: '/products/cold-smoked-smelt.webp',
    price: 24.61,
    perKg: false,
  },
  {
    i18nCode: 'koreanHerring',
    categoryI18nCode: CategoryRoute.cannedFish,
    image: '/products/korean-herring.webp',
    price: 25.02,
    perKg: false,
  },
  {
    i18nCode: 'salmonFillet',
    categoryI18nCode: CategoryRoute.saltedFish,
    image: '/products/salmon-fillet.webp',
    price: 580,
    perKg: true,
  },
  {
    i18nCode: 'driedBruise',
    categoryI18nCode: CategoryRoute.driedFish,
    image: '/products/dried-bruise.webp',
    price: 118.38,
    perKg: true,
  },
  {
    i18nCode: 'beefJerky',
    categoryI18nCode: CategoryRoute.driedFish,
    image: '/products/beef-jerky.webp',
    price: 249.78,
    perKg: true,
  },
]
